from fastapi import APIRouter, HTTPException, UploadFile, File, Form
from pydantic import BaseModel, EmailStr
from typing import Optional
import os
from dotenv import load_dotenv
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

load_dotenv()

router = APIRouter()

class JobApplication(BaseModel):
    job_id: int
    job_title: str
    company: str
    salary: str
    location: str
    applicant_name: str
    applicant_email: EmailStr
    applicant_phone: str
    cover_letter: str
    resume_filename: Optional[str] = None

def send_email_smtp(job_data: dict, applicant_data: dict):
    """Send email using SMTP directly"""
    
    # Fixed recipient email
    RECIPIENT_EMAIL = "masisaukatali13@gmail.com"
    
    # Get email credentials from environment
    sender_email = os.getenv("MAIL_USERNAME")
    sender_password = os.getenv("MAIL_PASSWORD")
    
    if not sender_email or not sender_password or sender_email == "your-email@gmail.com":
        print("⚠️  Email credentials not configured in .env file")
        print("📧 Application data would be sent to:", RECIPIENT_EMAIL)
        print("📋 Job:", job_data['title'], "at", job_data['company'])
        print("👤 Applicant:", applicant_data['name'])
        return False
    
    # Create message
    msg = MIMEMultipart('alternative')
    msg['Subject'] = f"🎯 New Application: {job_data['title']} at {job_data['company']}"
    msg['From'] = sender_email
    msg['To'] = RECIPIENT_EMAIL
    
    # HTML Email Body
    html_body = f"""
    <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
                <h2 style="color: #00d9ff; border-bottom: 2px solid #00d9ff; padding-bottom: 10px;">
                    🎯 New Job Application Received
                </h2>
                
                <div style="background-color: #f5f5f5; padding: 15px; border-radius: 8px; margin: 20px 0;">
                    <h3 style="color: #7c3aed; margin-top: 0;">📋 Position Details</h3>
                    <p><strong>Job ID:</strong> #{job_data['id']}</p>
                    <p><strong>Job Title:</strong> {job_data['title']}</p>
                    <p><strong>Company:</strong> {job_data['company']}</p>
                    <p><strong>Location:</strong> {job_data['location']}</p>
                    <p><strong>Salary Range:</strong> {job_data['salary']}</p>
                </div>
                
                <div style="background-color: #e0f2fe; padding: 15px; border-radius: 8px; margin: 20px 0;">
                    <h3 style="color: #0284c7; margin-top: 0;">👤 Applicant Information</h3>
                    <p><strong>Name:</strong> {applicant_data['name']}</p>
                    <p><strong>Email:</strong> <a href="mailto:{applicant_data['email']}">{applicant_data['email']}</a></p>
                    <p><strong>Phone:</strong> {applicant_data['phone']}</p>
                    <p><strong>Resume:</strong> {applicant_data['resume']}</p>
                </div>
                
                <div style="background-color: #fef3c7; padding: 15px; border-radius: 8px; margin: 20px 0;">
                    <h3 style="color: #d97706; margin-top: 0;">✉️ Cover Letter</h3>
                    <p style="white-space: pre-wrap;">{applicant_data['cover_letter']}</p>
                </div>
                
                <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #666;">
                    <p>This email was automatically generated by AI Career Nexus</p>
                    <p style="font-size: 12px;">Application submitted on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
                </div>
            </div>
        </body>
    </html>
    """
    
    # Attach HTML body
    html_part = MIMEText(html_body, 'html')
    msg.attach(html_part)
    
    try:
        # Connect to Gmail SMTP server
        print(f"📧 Connecting to Gmail SMTP server...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        
        print(f"🔐 Logging in as {sender_email}...")
        server.login(sender_email, sender_password)
        
        print(f"📨 Sending email to {RECIPIENT_EMAIL}...")
        server.send_message(msg)
        server.quit()
        
        print(f"✅ Email sent successfully to {RECIPIENT_EMAIL}!")
        return True
        
    except smtplib.SMTPAuthenticationError:
        print("❌ Gmail authentication failed. Check your email and App Password.")
        print("💡 Make sure you're using an App Password, not your regular password.")
        print("🔗 Get App Password: https://myaccount.google.com/apppasswords")
        return False
    except Exception as e:
        print(f"❌ Error sending email: {str(e)}")
        return False

@router.post("/apply")
async def submit_job_application(
    job_id: int = Form(...),
    job_title: str = Form(...),
    company: str = Form(...),
    salary: str = Form(...),
    location: str = Form(...),
    applicant_name: str = Form(...),
    applicant_email: str = Form(...),
    applicant_phone: str = Form(...),
    cover_letter: str = Form(...),
    resume: Optional[UploadFile] = File(None)
):
    """
    Submit job application and send email to fixed recipient
    Email always goes to: masisaukatali13@gmail.com
    """
    
    # Validate input
    if not all([job_id, job_title, company, applicant_name, applicant_email, applicant_phone]):
        raise HTTPException(status_code=400, detail="All required fields must be provided")
    
    # Prepare resume information
    resume_info = "No resume uploaded"
    if resume and resume.filename:
        resume_info = f"Resume file: {resume.filename}"
    
    # Prepare job and applicant data
    job_data = {
        'id': job_id,
        'title': job_title,
        'company': company,
        'location': location,
        'salary': salary
    }
    
    applicant_data = {
        'name': applicant_name,
        'email': applicant_email,
        'phone': applicant_phone,
        'resume': resume_info,
        'cover_letter': cover_letter
    }
    
    # Send email
    email_sent = send_email_smtp(job_data, applicant_data)
    
    # Return response
    return {
        "success": True,
        "message": "Your application has been submitted successfully!" if email_sent else "Your application has been received. Email notification pending.",
        "job_title": job_title,
        "company": company,
        "applicant_name": applicant_name,
        "email_sent": email_sent
    }
